# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('main_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('ab', 'Assets balance sheet'), ('pb', 'Passive balance sheet'), ('is', 'Income Statement'), ('cf', 'Cash flow')], max_length=2)),
                ('url', models.CharField(max_length=200)),
                ('version', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bovespa.Company')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bovespa.Date')),
            ],
        ),
        migrations.CreateModel(
            name='ValueFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bovespa.Account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bovespa.Company')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bovespa.Date')),
                ('fin_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bovespa.FinancialReport')),
            ],
        ),
    ]
