# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bovespa', '0002_company_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='kind',
        ),
        migrations.AddField(
            model_name='financialreport',
            name='main_url',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
