# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bovespa', '0003_auto_20170530_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='report_type',
            field=models.CharField(choices=[('ab', 'Balanço Patrimonial Ativo'), ('pb', 'Passive balance sheet'), ('is', 'Income Statement'), ('cf', 'Cash flow')], max_length=2),
        ),
    ]
