# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bovespa', '0004_auto_20170530_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='main_url',
            field=models.CharField(max_length=200),
        ),
    ]
