# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bovespa', '0006_auto_20170530_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuefact',
            name='company',
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='report_type',
            field=models.CharField(choices=[('ab', 'Balanço Patrimonial Ativo'), ('pb', 'Balanço Patrimonial Passivo'), ('is', 'Demonstração do Resultado'), ('cf', 'Demonstração do Fluxo de Caixa')], max_length=2),
        ),
    ]
