# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bovespa', '0007_auto_20170530_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ibovespa',
            field=models.BooleanField(default=False),
        ),
    ]
