# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bovespa', '0008_company_ibovespa'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='segment',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='report_type',
            field=models.CharField(choices=[('ab', 'Balanço Patrimonial Ativo'), ('pb', 'Balanço Patrimonial Passivo'), ('is', 'Demonstração do Resultado'), ('cf', 'Demonstração do Fluxo de Caixa'), ('da', 'Demonstração do Resultado Abrangente'), ('va', 'Demonstração de Valor Adicionado')], max_length=2),
        ),
    ]
