# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bovespa', '0009_auto_20170604_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='symbol',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
