# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-22 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bovespa', '0010_auto_20170604_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='inserted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='company',
            table='companies',
        ),
    ]
