# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bovespa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='kind',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
