# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import src_proto.data_pb2 as data__pb2


class RoutePriceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.TraversePrice = channel.unary_unary(
        '/stream.RoutePrice/TraversePrice',
        request_serializer=data__pb2.InputPrice.SerializeToString,
        response_deserializer=data__pb2.PredictedPrice.FromString,
        )


class RoutePriceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def TraversePrice(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RoutePriceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'TraversePrice': grpc.unary_unary_rpc_method_handler(
          servicer.TraversePrice,
          request_deserializer=data__pb2.InputPrice.FromString,
          response_serializer=data__pb2.PredictedPrice.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'stream.RoutePrice', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
