# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='stream',
  syntax='proto3',
  serialized_pb=_b('\n\ndata.proto\x12\x06stream\"=\n\nInputPrice\x12\x10\n\x08\x64\x61tetime\x18\x01 \x01(\t\x12\r\n\x05\x63lose\x18\x02 \x01(\x02\x12\x0e\n\x06symbol\x18\x03 \x01(\t\"A\n\x0ePredictedPrice\x12\x10\n\x08\x64\x61tetime\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\x12\x0e\n\x06symbol\x18\x03 \x01(\t2K\n\nRoutePrice\x12=\n\rTraversePrice\x12\x12.stream.InputPrice\x1a\x16.stream.PredictedPrice\"\x00\x62\x06proto3')
)




_INPUTPRICE = _descriptor.Descriptor(
  name='InputPrice',
  full_name='stream.InputPrice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='datetime', full_name='stream.InputPrice.datetime', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='close', full_name='stream.InputPrice.close', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='stream.InputPrice.symbol', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=83,
)


_PREDICTEDPRICE = _descriptor.Descriptor(
  name='PredictedPrice',
  full_name='stream.PredictedPrice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='datetime', full_name='stream.PredictedPrice.datetime', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='stream.PredictedPrice.price', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='stream.PredictedPrice.symbol', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=150,
)

DESCRIPTOR.message_types_by_name['InputPrice'] = _INPUTPRICE
DESCRIPTOR.message_types_by_name['PredictedPrice'] = _PREDICTEDPRICE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputPrice = _reflection.GeneratedProtocolMessageType('InputPrice', (_message.Message,), dict(
  DESCRIPTOR = _INPUTPRICE,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:stream.InputPrice)
  ))
_sym_db.RegisterMessage(InputPrice)

PredictedPrice = _reflection.GeneratedProtocolMessageType('PredictedPrice', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTEDPRICE,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:stream.PredictedPrice)
  ))
_sym_db.RegisterMessage(PredictedPrice)



_ROUTEPRICE = _descriptor.ServiceDescriptor(
  name='RoutePrice',
  full_name='stream.RoutePrice',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=152,
  serialized_end=227,
  methods=[
  _descriptor.MethodDescriptor(
    name='TraversePrice',
    full_name='stream.RoutePrice.TraversePrice',
    index=0,
    containing_service=None,
    input_type=_INPUTPRICE,
    output_type=_PREDICTEDPRICE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROUTEPRICE)

DESCRIPTOR.services_by_name['RoutePrice'] = _ROUTEPRICE

# @@protoc_insertion_point(module_scope)
