# Generated by Django 2.1 on 2018-08-16 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=50)),
                ('main_url', models.CharField(max_length=255)),
                ('ibovespa', models.BooleanField(default=False)),
                ('segment', models.CharField(default='', max_length=200)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('ab', 'Balanço Patrimonial Ativo'), ('pb', 'Balanço Patrimonial Passivo'), ('is', 'Demonstração do Resultado'), ('cf', 'Demonstração do Fluxo de Caixa'), ('da', 'Demonstração do Resultado Abrangente'), ('va', 'Demonstração de Valor Adicionado')], max_length=2)),
                ('main_url', models.CharField(max_length=200)),
                ('url', models.TextField()),
                ('version', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmf.Company')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmf.Date')),
            ],
        ),
        migrations.CreateModel(
            name='ValueFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmf.Account')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmf.Date')),
                ('fin_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmf.FinancialReport')),
            ],
        ),
    ]
