# Generated by Django 2.1 on 2018-08-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmf', '0002_auto_20180816_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
