on: 
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 22.2
          elixir-version: 1.9.4
      - run: |
          cd web/ 
          mix deps.get
          mix absinthe.schema.json --schema WebWeb.Schema pr-schema.json

      - name: gql-pull
        uses: knabben/gql-pull@0.0.6
        id: pull
        with:
          source: schema.json
          destination: pr-schema.json

      - name: Bring diff to PR
        uses: unsplash/comment-on-pr@master
        with:
          msg: ${{ steps.pull.outputs.output }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}